apiVersion: v1
kind: Service
metadata:
  name: split-alert
  namespace: monitoring
spec:
  selector:
    app: split-alert
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP